"""initial_postgresql_schema

Revision ID: a142eac68c7a
Revises:
Create Date: 2026-04-13 00:59:27.774717

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a142eac68c7a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # teaching_sessions 必须最先创建（被其他表的外键引用）
    op.create_table('teaching_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teaching_mode', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('students_config', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoint_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('receiver', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message_history', sa.JSON(), nullable=False),
    sa.Column('teaching_summary', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('excellent', 'average', 'basic', name='studentlevel'), nullable=False),
    sa.Column('attitude', sa.Enum('active', 'neutral', 'passive', name='studentattitude'), nullable=False),
    sa.Column('learning_ability', sa.Integer(), nullable=False),
    sa.Column('learned_concepts', sa.JSON(), nullable=False),
    sa.Column('confused_points', sa.JSON(), nullable=False),
    sa.Column('questions_asked', sa.JSON(), nullable=False),
    sa.Column('initial_knowledge_level', sa.Float(), nullable=False),
    sa.Column('current_knowledge_level', sa.Float(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_memories_session_id', 'student_memories', ['session_id'], unique=False)
    op.create_index('ix_student_memories_session_student', 'student_memories', ['session_id', 'student_name'], unique=False)
    op.create_table('teacher_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('covered_topics', sa.JSON(), nullable=False),
    sa.Column('student_questions', sa.JSON(), nullable=False),
    sa.Column('student_participation', sa.JSON(), nullable=False),
    sa.Column('teaching_progress', sa.Float(), nullable=False),
    sa.Column('student_misconceptions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_memories')
    op.drop_index('ix_student_memories_session_student', table_name='student_memories')
    op.drop_index('ix_student_memories_session_id', table_name='student_memories')
    op.drop_table('student_memories')
    op.drop_table('session_memories')
    op.drop_table('messages')
    op.drop_table('teaching_sessions')
    op.drop_table('checkpoint_plans')
    # PostgreSQL ENUM 类型需要显式删除（Alembic 不会自动生成 DROP TYPE）
    op.execute("DROP TYPE IF EXISTS studentlevel")
    op.execute("DROP TYPE IF EXISTS studentattitude")
    # ### end Alembic commands ###
